name: Android Build

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Обновлено до v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant gradlew permissions
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Исправлено на v4
        with:
          name: winlator-release
          path: app/build/outputs/apk/release/*.apk
